---
title: "R Notebook"
output: html_notebook
---


```{r}
library(devtools)
library(DBI)
# library(mongolite)
# library(RColorBrewer)
# library(arules)
library(dplyr)
library(tidyr)
library(lubridate)
# library(tidyverse)
library(RSQLite)
library(data.table)
```

# Importation des données

```{r}
filename1 <- "/Users/oscarconan/Desktop/atelier_22-07.db"
filename2 <- "/Users/oscarconan/Desktop/atelier_12-07.db"
sqlite.driver <- dbDriver("SQLite")
db1 <- dbConnect(sqlite.driver, dbname = filename1)
db2 <- dbConnect(sqlite.driver, dbname = filename2)

df1 <- dbReadTable(db1,"all_data")
df2 <- dbReadTable(db2,"all_data")
```


# Transformation des données

```{r}

# On met en factor 
df1 = df1 %>% mutate_if(is.numeric, as.factor)
df2 = df2 %>% mutate_if(is.numeric, as.factor)

# On traite les dates
df1[,"Datetime"] = ymd_hms(df1[,"Datetime"])
df2[,"Datetime"] = ymd_hms(df2[,"Datetime"])

# Etude des données
summary(df1)
summary(df2)

# On enlève les 2 
df2 = df2 %>% filter(((t2_casque !=2) & (t2_veste !=2) & (t2_visiere !=2) & (t2_col !=2) & (t1_gant_gauche != 2)) %>% replace_na(TRUE))
```



```{r}
# Création de la colonne danger
df2 = df2 %>% mutate(danger = 0)
df1 = df1 %>% mutate(danger = 0)
```


```{r}
## DF1

# On enlève le scénario 3 car il y a des erreurs dedans : les gants ne sont pas détectés à des endroits ce qui vient fausser les résultats, et on a pas de scénario 4 caer aucune erreur dans le excel

df1  = df1 %>% filter(Scenario==c(1,2,5))


# Scenario 1
df1[ df1$Scenario == 1 & df1$Datetime >= as.POSIXct("2021-07-22 10:54:58",tz="UTC") & df1$Datetime < as.POSIXct("2021-07-22 10:57:39",tz="UTC"),"danger"] = 1


# Scenario 2
df1[ df1$Scenario == 2 & df1$Datetime >= as.POSIXct("2021-07-22 11:03:31",tz="UTC") & df1$Datetime < as.POSIXct("2021-07-22 11:04:49",tz="UTC"),"danger"] = 1

# Scenario 5
df1[ df1$Scenario == 5 & df1$Datetime >= as.POSIXct("2021-07-22 14:53:01",tz="UTC") & df1$Datetime < as.POSIXct("2021-07-22 14:54:00",tz="UTC"),"danger"] = 1



df1 = df1 %>% mutate_if(is.numeric, as.factor)
summary(df1)
```


```{r}

## DF2

#df2 %>% filter(Scenario == 1, Datetime > as.POSIXct("2021-07-12 10:52:00",tz="UTC"), Datetime < as.POSIXct("2021-07-12 10:59:00",tz="UTC")) %>% mutate(danger=1)


# Scenario 1
df2[ df2$Scenario == 1 & df2$Datetime >= as.POSIXct("2021-07-12 10:52:58",tz="UTC") & df2$Datetime < as.POSIXct("2021-07-12 10:59:04",tz="UTC"),"danger"] = 1
df2[ df2$Scenario == 1 & df2$Datetime > as.POSIXct("2021-07-12 11:01:56",tz="UTC") & df2$Datetime < as.POSIXct("2021-07-12 11:03:00",tz="UTC"),"danger"] = 1


# Scenario 2
df2[ df2$Scenario == 2 & df2$Datetime >= as.POSIXct("2021-07-12 11:10:00",tz="UTC") & df2$Datetime < as.POSIXct("2021-07-12 11:13:52",tz="UTC"),"danger"] = 1
df2[ df2$Scenario == 2 & df2$Datetime > as.POSIXct("2021-07-12 11:14:32",tz="UTC") & df2$Datetime < as.POSIXct("2021-07-12 11:15:33",tz="UTC"),"danger"] = 1

# Scenario 3
df2[ df2$Scenario == 3 & df2$Datetime >= as.POSIXct("2021-07-12 14:22:06",tz="UTC") & df2$Datetime < as.POSIXct("2021-07-12 14:25:01",tz="UTC"),"danger"] = 1

# Scenario 4
df2[ df2$Scenario == 4 & df2$Datetime >= as.POSIXct("2021-07-12 14:29:38",tz="UTC") & df2$Datetime < as.POSIXct("2021-07-12 14:30:16",tz="UTC"),"danger"] = 1

# Scenario 5
# PAS D'HEURES DANS LE EXCEL

# Scenario 6
# Problème scénario, on l'ignore

df2 = df2 %>% mutate_if(is.numeric, as.factor)
summary(df2)
df2
```
# Séparation du jeu de données 

```{r}
## DF1
# On sépare en deux échantillons
set.seed(300)
indtrain = sample(1:floor(0.75*nrow(df1)),nrow(df1),replace=TRUE)
indtest = setdiff(1:nrow(df1),indtrain)

train_df1 = df1[indtrain,]
test_df1 = df1[indtest,]

```

```{r}
## DF2
# On sépare en deux échantillons
set.seed(300)
indtrain = sample(1:floor(0.75*nrow(df2)),nrow(df2),replace=TRUE)
indtest = setdiff(1:nrow(df2),indtrain)

train_df2 = df2[indtrain,]
test_df2 = df2[indtest,]



```

# Isolation forest

```{r}
# Premier modèle DF1


library(isotree)

train_df1 %>% select(-Scenario,-Timestamp,-Datetime)
test_df1 %>% select(-Scenario,-Timestamp,-Datetime)

# Model fitting
model = isolation.forest(train_df1)

# Prediction
pred = predict(model,test_df1)
pred_sort = sort(pred,decreasing=TRUE)[0:50]
pred_sort

# Si on fixe un seuil a 0.6 : 

df1[c(190,191,192,193,189,173,174,175,181,182,183,185),]

# Les premières sont bien des anomalies, ici le seuil doit être différent et peut etre pas assze de données ? Dèjà bcp moins de danger. Mais semble fonctionner quand meme !


```



```{r}
# Premier modèle DF2

library(isotree)

train_df2 %>% select(-Scenario,-Timestamp,-Datetime)
test_df2 %>% select(-Scenario,-Timestamp,-Datetime)

# Model fitting
model = isolation.forest(train_df2)

# Prediction
pred = predict(model,test_df2)
pred_sort = sort(pred,decreasing=TRUE)[0:50]
pred_sort[pred_sort>=0.6]

# Si on fixe un seuil a 0.6 : 

df2[c(39,808,822,823,821,819,820,811,812,810,809,807,936,930,793,799),"danger"]
# Bons résultats !! Mais que sur le scénario 3 du coup comme l'algo isole les données semblables

```






